parameters:

    #webpay.api.endpoint: "https://api.webpay.com/v2/"
    webpay.controller.route.name: "webpay_execute"
    webpay.form.type.wrapper.class: "PaymentSuite\\WebpayBundle\\Services\\Wrapper\\WebpayTypeWrapper"
    #webpay.transaction.wrapper.class: "PaymentSuite\\WebpayBundle\\Services\\Wrapper\\WebpayTransactionWrapper"
    #webpay.manager.class: "PaymentSuite\\WebpayBundle\\Services\\WebpayManager"
    #webpay.twig.extension.class: "PaymentSuite\\WebpayBundle\\Twig\\WebpayExtension"
    webpay.routes.loader.class: "PaymentSuite\\WebpayBundle\\Router\\WebpayRoutesLoader"
